--
-- This file is automatically generated for your cluster
-- All setup and initialization is performed when the VM in this cluster starts
--


-- PolyBase server setup

sp_configure 'allow polybase export', 1;
GO

sp_configure 'hadoop connectivity', 7;   
RECONFIGURE;
GO

ALTER DATABASE AdventureWorks2012 SET COMPATIBILITY_LEVEL = 120;  
GO

-- PolyBase database setup

USE AdventureWorks2012

CREATE MASTER KEY ENCRYPTION BY PASSWORD = '$(MASTER_KEY)';

CREATE EXTERNAL FILE FORMAT CSVFormat WITH (
  FORMAT_TYPE = DELIMITEDTEXT,
  FORMAT_OPTIONS (FIELD_TERMINATOR = ',', USE_TYPE_DEFAULT = TRUE)
);

CREATE EXTERNAL FILE FORMAT PipeFormat WITH (
  FORMAT_TYPE = DELIMITEDTEXT,
  FORMAT_OPTIONS (FIELD_TERMINATOR = '|', USE_TYPE_DEFAULT = TRUE)
);

-- Hyprid execution setup

CREATE DATABASE SCOPED CREDENTIAL BlobStorageCredential WITH IDENTITY = '$(STORAGE_ACCOUNT_NAME)', Secret = '$(STORAGE_ACCOUNT_KEY)';

CREATE EXTERNAL DATA SOURCE AzureBlob WITH (
  TYPE = HADOOP,
  LOCATION = 'wasbs://$(STORAGE_CONTAINER_NAME)@$(STORAGE_ACCOUNT_KEY).blob.core.windows.net',
  CREDENTIAL = AzureStorageCredential
);

CREATE EXTERNAL TABLE Product_Blob (
  ProductID INT,
  Name NVARCHAR(50),
  ProductNumber nvarchar(25),
  MakeFlag BIT,
  FinishedGoodsFlag BIT,
  Color NVARCHAR(15),
  SafetyStockLevel smallint,
  ReorderPoint smallint,
  StandardCost money,
  ListPrice money,
  Size NVARCHAR(5) ,
  SizeUnitMeasureCode NCHAR(3) ,
  WeightUnitMeasureCode NCHAR(3),
  Weight decimal(8, 2),
  DaysToManufacture int,
  ProductLine NCHAR(2),
  Class NCHAR(2),
  Style NCHAR(2),
  ProductSubcategoryID int,
  ProductModelID int,
  SellStartDate datetime,
  SellEndDate datetime ,
  DiscontinuedDate datetime,
  rowguid NVARCHAR (255),
  ModifiedDate datetime
)
WITH (LOCATION='/product',
  DATA_SOURCE = AzureBlob,
  FILE_FORMAT = CSVFormat
);

-- Predicate pushdown setup

CREATE DATABASE SCOPED CREDENTIAL HDIStorageCredential WITH IDENTITY = '$(HDI_USERNAME)', Secret = '$(HDI_PASSWORD)';

CREATE EXTERNAL DATA SOURCE HDInsight WITH (  
  TYPE = HADOOP,   
  LOCATION ='hdfs://$(HDI_NAMENODE_HOST):8020',   
  RESOURCE_MANAGER_LOCATION = '$(HDI_RESOURCE_MANAGER_HOST):8050',   
  CREDENTIAL = HDIStorageCredential      
);

CREATE EXTERNAL TABLE Product_HDFS (
  ProductID INT,
  Name NVARCHAR(50),
  ProductNumber nvarchar(25),
  MakeFlag BIT,
  FinishedGoodsFlag BIT,
  Color NVARCHAR(15),
  SafetyStockLevel smallint,
  ReorderPoint smallint,
  StandardCost money,
  ListPrice money,
  Size NVARCHAR(5) ,
  SizeUnitMeasureCode NCHAR(3) ,
  WeightUnitMeasureCode NCHAR(3),
  Weight decimal(8, 2),
  DaysToManufacture int,
  ProductLine NCHAR(2),
  Class NCHAR(2),
  Style NCHAR(2),
  ProductSubcategoryID int,
  ProductModelID int,
  SellStartDate datetime,
  SellEndDate datetime ,
  DiscontinuedDate datetime,
  rowguid NVARCHAR (255),
  ModifiedDate datetime
)
WITH (LOCATION='/product',
  DATA_SOURCE = HDInsight,
  FILE_FORMAT = PipeFormat
);

INSERT INTO 
  dbo.Product_HDFS 
SELECT
  * 
FROM 
  Production.Product;